const STORAGE_KEY = 'ruangstock-inventory';
const SESSION_KEY = 'ruangstock-session';
const USERS = { sastra: { name: 'Rahmatullah Sastra Ardiansyah', short: 'Sastra' }, ikhsan: { name: 'Rahmad Ikhsan Maulana', short: 'Ikhsan' } };
const PROFILE_KEY = 'ruangstock-profiles';
let profiles = JSON.parse(localStorage.getItem(PROFILE_KEY) || '{}');
const ROOMS = ['Lab 1', 'Lab 2', 'Lab 3', 'Lab 4', 'Skaweb', 'Axio 1', 'Axio 2', 'Axio 3', 'Perpustakaan Bawah', 'Perpustakaan Atas', 'Ruang A2.1', 'Ruang A2.2', 'Ruang A2.3', 'Ruang A2.4', 'Ruang A2.5', 'Ruang A2.6', 'Ruang A2.7', 'Ruang B2.1', 'Ruang B2.2', 'Ruang B2.3', 'Ruang C1.1', 'Ruang C1.2', 'Ruang C1.3', 'Ruang C1.4', 'Ruang C2.1', 'Ruang C2.2', 'Ruang D1.1', 'Ruang D1.2', 'Ruang D1.3', 'Ruang D1.4', 'Ruang D1.5', 'Ruang D2.1', 'Ruang D2.2', 'Ruang D2.3', 'Ruang D2.4', 'Ruang D2.5', 'Lab Korea', 'Lab Jepang', 'Ruang Guru'];
let items = JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]'), deferredPrompt;
const $ = id => document.getElementById(id);
const splash = $('splashScreen'), loginScreen = $('loginScreen'), app = $('app'), dialog = $('itemDialog'), form = $('itemForm');
const save = () => { localStorage.setItem(STORAGE_KEY, JSON.stringify(items)); render() };
const toast = (message, type = 'success') => { const el = $('toast'); el.innerHTML = `<i class="fa-solid ${type === 'danger' ? 'fa-trash-can' : type === 'info' ? 'fa-circle-info' : 'fa-circle-check'}"></i><span>${message}</span>`; el.className = `toast ${type} show`; clearTimeout(window.toastTimer); window.toastTimer = setTimeout(() => el.classList.remove('show'), 2800) };
function actionAnimation(type = 'success') { document.body.classList.remove('action-success', 'action-danger', 'action-info'); void document.body.offsetWidth; document.body.classList.add(`action-${type}`); setTimeout(() => document.body.classList.remove(`action-${type}`), 900) }
function formatDate() { return new Intl.DateTimeFormat('id-ID', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date()) }
function getProfile(user) { return profiles[user] || { name: USERS[user].name, password: 'smk1krian', photo: '', changedAt: 0 } }
function startSession(user) { localStorage.setItem(SESSION_KEY, user); const profile = getProfile(user); $('activeUser').textContent = profile.name; $('userAvatar').textContent = profile.name.charAt(0).toUpperCase(); if (profile.photo) { $('userAvatar').innerHTML = `<img src="${profile.photo}" alt="Foto profil">` } $('profileName').value = profile.name; loginScreen.classList.add('is-hidden'); app.classList.remove('is-hidden'); document.body.style.overflow = ''; render() }
function showLogin() { app.classList.add('is-hidden'); loginScreen.classList.remove('is-hidden'); document.body.style.overflow = 'hidden'; $('loginPassword').value = ''; $('loginUser').value = '' }
function render() {
    const query = $('searchInput').value.toLowerCase().trim(), room = $('roomFilter').value, condition = $('conditionFilter').value;
    const filtered = items.filter(i => (i.name.toLowerCase().includes(query) || i.code.toLowerCase().includes(query)) && (!room || i.room === room) && (!condition || i.condition === condition));
    const total = items.reduce((sum, i) => sum + Number(i.quantity), 0), good = items.filter(i => i.condition === 'Baik').reduce((sum, i) => sum + Number(i.quantity), 0), bad = total - good;
    $('totalCount').textContent = total; $('goodCount').textContent = good; $('badCount').textContent = bad; $('goodPercent').textContent = total ? Math.round(good / total * 100) + '%' : '0%'; $('goodProgress').style.width = (total ? good / total * 100 : 0) + '%'; $('badProgress').style.width = (total ? bad / total * 100 : 0) + '%'; $('roomCount').textContent = new Set(items.map(i => i.room)).size; $('lastUpdated').textContent = items.length ? 'Diperbarui ' + formatDate() : 'Belum ada data';
    const current = room; $('roomFilter').innerHTML = '<option value="">Semua ruangan</option>' + ROOMS.map(r => `<option value="${escapeHtml(r)}" ${r === current ? 'selected' : ''}>${escapeHtml(r)}</option>`).join('');
    $('inventoryList').innerHTML = filtered.map((i, index) => `<article class="item-card" style="animation-delay:${index * 35}ms"><div><div class="item-name">${escapeHtml(i.name)}</div><div class="item-code">${escapeHtml(i.code)}</div></div><div class="item-meta item-room"><b>Ruangan</b>${escapeHtml(i.room)}</div><div class="item-meta"><b>Jumlah</b>${i.quantity} unit</div><div><span class="condition ${i.condition === 'Baik' ? 'good' : i.condition === 'Rusak Ringan' ? 'light' : 'heavy'}">${i.condition}</span></div><div class="item-actions"><button class="action edit-action" data-id="${i.id}" title="Edit"><i class="fa-solid fa-pen"></i></button><button class="action delete-action" data-id="${i.id}" title="Hapus"><i class="fa-solid fa-trash"></i></button></div></article>`).join('');
    $('emptyState').style.display = filtered.length ? 'none' : 'block'; document.querySelectorAll('.edit-action').forEach(b => b.onclick = () => openEdit(b.dataset.id)); document.querySelectorAll('.delete-action').forEach(b => b.onclick = () => deleteItem(b.dataset.id));
}
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c])) }
function populateRooms(selected = '') { const options = '<option value="">Pilih ruangan</option>' + ROOMS.map(r => `<option value="${escapeHtml(r)}" ${r === selected ? 'selected' : ''}>${escapeHtml(r)}</option>`).join(''); $('itemRoom').innerHTML = options }
function openAdd() { form.reset(); populateRooms(); $('itemId').value = ''; $('itemQuantity').value = 1; $('modalTitle').textContent = 'Tambah barang'; dialog.showModal(); setTimeout(() => $('itemName').focus(), 100) }
function openEdit(id) { const item = items.find(i => i.id === id); if (!item) return; $('modalTitle').textContent = 'Edit barang'; $('itemId').value = item.id; $('itemName').value = item.name; $('itemCode').value = item.code; populateRooms(item.room); $('itemQuantity').value = item.quantity; $('itemCondition').value = item.condition; dialog.showModal() }
function deleteItem(id) { const item = items.find(i => i.id === id); if (confirm('Apakah Anda yakin ingin menghapus data ini?')) { const card = document.querySelector(`[data-id="${id}"]`)?.closest('.item-card'); card?.classList.add('removing'); setTimeout(() => { items = items.filter(i => i.id !== id); save(); actionAnimation('danger'); toast(`${item.name} berhasil dihapus`, 'danger') }, 360) } }
$('loginForm').addEventListener('submit', e => { e.preventDefault(); const user = $('loginUser').value, password = $('loginPassword').value; if (user && password === getProfile(user).password) { startSession(user); $('loginError').textContent = '' } else { $('loginError').textContent = 'Akun atau password salah. Password awal: smk1krian' } });
$('togglePassword').onclick = () => { const input = $('loginPassword'), icon = $('togglePassword i'); input.type = input.type === 'password' ? 'text' : 'password'; $('togglePassword').innerHTML = `<i class="fa-solid fa-eye${input.type === 'password' ? '' : '-slash'}"></i>` };
$('logoutBtn').onclick = () => { localStorage.removeItem(SESSION_KEY); showLogin(); toast('Kamu sudah keluar dari RuangStock') };
function openProfile() { const user = localStorage.getItem(SESSION_KEY), profile = getProfile(user); $('profileName').value = profile.name; $('profilePassword').value = ''; $('profilePhoto').value = ''; $('profileError').textContent = ''; $('profilePreview').src = profile.photo || `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100" rx="50" fill="#1177e8"/><text x="50" y="62" text-anchor="middle" fill="white" font-size="40" font-family="Arial">${profile.name.charAt(0).toUpperCase()}</text></svg>`)}`; const remaining = profile.changedAt ? new Date(profile.changedAt + 30 * 24 * 60 * 60 * 1000) : null; $('profileLimit').textContent = remaining && remaining > Date.now() ? `Nama dan password dapat diganti lagi pada ${remaining.toLocaleDateString('id-ID')}.` : 'Nama dan password tersedia untuk diperbarui bulan ini.'; $('profileDialog').showModal() }
$('profileButton').onclick = openProfile; $('userAvatar').onclick = openProfile; $('closeProfile').onclick = () => $('profileDialog').close(); $('cancelProfile').onclick = () => $('profileDialog').close();
$('profilePhoto').onchange = e => { const file = e.target.files[0]; if (!file) return; if (!['image/jpeg', 'image/png'].includes(file.type)) { e.target.value = ''; $('profileError').textContent = 'Foto harus JPG, JPEG, atau PNG.'; return } const reader = new FileReader(); reader.onload = () => { $('profilePreview').src = reader.result; $('profilePreview').dataset.photo = reader.result }; reader.readAsDataURL(file) };
$('profileForm').addEventListener('submit', e => { e.preventDefault(); const user = localStorage.getItem(SESSION_KEY), profile = getProfile(user), now = Date.now(), locked = profile.changedAt && now < profile.changedAt + 30 * 24 * 60 * 60 * 1000, name = $('profileName').value.trim(), password = $('profilePassword').value.trim(); if (locked && (name !== profile.name || password)) { $('profileError').textContent = 'Nama dan password hanya dapat diganti 1 kali dalam sebulan.'; return } profiles[user] = { ...profile, name, password: password || profile.password, photo: $('profilePreview').dataset.photo || profile.photo, changedAt: (name !== profile.name || password) ? now : profile.changedAt }; localStorage.setItem(PROFILE_KEY, JSON.stringify(profiles)); $('profileDialog').close(); startSession(user); actionAnimation('success'); toast('Profil berhasil diperbarui') });
form.addEventListener('submit', e => { e.preventDefault(); const id = $('itemId').value, data = { id: id || crypto.randomUUID(), name: $('itemName').value.trim(), code: $('itemCode').value.trim().toUpperCase(), room: $('itemRoom').value.trim(), quantity: Number($('itemQuantity').value), condition: $('itemCondition').value }; if (id) { items = items.map(i => i.id === id ? data : i); toast('Data berhasil diperbarui'); actionAnimation('info') } else { items.unshift(data); toast('Barang berhasil ditambahkan'); actionAnimation('success') } save(); dialog.close() });
$('addButton').onclick = openAdd; $('emptyAddButton').onclick = openAdd; $('closeDialog').onclick = () => dialog.close(); $('cancelDialog').onclick = () => dialog.close(); $('searchInput').oninput = render; $('roomFilter').onchange = render; $('conditionFilter').onchange = render;
$('themeToggle').onclick = () => { document.body.classList.toggle('dark'); localStorage.setItem('ruangstock-dark', document.body.classList.contains('dark')); $('themeToggle').querySelector('i').className = document.body.classList.contains('dark') ? 'fa-solid fa-sun' : 'fa-solid fa-moon' };
$('exportBtn').onclick = () => { const blob = new Blob([JSON.stringify(items, null, 2)], { type: 'application/json' }), url = URL.createObjectURL(blob), a = document.createElement('a'); a.href = url; a.download = 'backup-inventaris.json'; a.click(); URL.revokeObjectURL(url); actionAnimation('info'); toast('Data berhasil diekspor', 'info') };
window.addEventListener('beforeinstallprompt', e => { e.preventDefault(); deferredPrompt = e; $('installBtn').classList.remove('hidden') }); $('installBtn').onclick = async () => { if (!deferredPrompt) return; deferredPrompt.prompt(); deferredPrompt = null; $('installBtn').classList.add('hidden') };
if (localStorage.getItem('ruangstock-dark') === 'true') { document.body.classList.add('dark'); $('themeToggle').querySelector('i').className = 'fa-solid fa-sun' }
let loadingProgress = 0; const loadingTimer = setInterval(() => { loadingProgress = Math.min(100, loadingProgress + Math.ceil(Math.random() * 13)); $('loadingPercent').textContent = loadingProgress + '%'; $('loadingText').textContent = loadingProgress < 35 ? 'Menyiapkan ruang kerja...' : loadingProgress < 70 ? 'Memuat inventaris sekolah...' : 'Hampir selesai...'; if (loadingProgress >= 100) clearInterval(loadingTimer) }, 180);
const session = localStorage.getItem(SESSION_KEY); if (session && USERS[session]) startSession(session); else { app.classList.add('is-hidden'); loginScreen.classList.add('is-hidden'); document.body.style.overflow = 'hidden'; setTimeout(() => { splash.remove(); loginScreen.classList.remove('is-hidden') }, 2600) } populateRooms(); render();
if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('service-worker.js').catch(console.error));
